platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.4'
pod 'SFHFKeychainUtils'
pod 'SBJson'
pod 'SDURLCache'
pod 'SSKeychain'
pod 'Reachability'
pod 'MXSegmentedPager'
pod 'M13ProgressSuite', '~> 1.2.7'
pod 'BaiduMapKit'
pod 'Google-Maps-iOS-SDK', '~> 1.4.3'
