platform :ios, '7.0'
pod 'AFNetworking'
pod 'SSToolkit'
pod 'ConciseKit'
pod 'MagicalRecord'
pod 'SFHFKeychainUtils'
pod 'SBJson'
pod 'SDURLCache'
pod 'SSKeychain'
pod 'Reachability'
pod 'JSBadgeView'
pod 'MXSegmentedPager'
pod 'M13ProgressSuite', '~> 1.2.7'
